### ISSUE TITLE
Tracking issue: Release on Play Store

### ISSUE THREAD

**Issue by bugadani** [bugadani/NotiFilter#12]
- [ ] Add app icon
 - [ ] Improve app strings
 - [x] Improve app list performance
 - [ ] Add crash logging
 - [ ] Add spash screen
 - [ ] UX improvements (#28 #29)
